name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependências
        working-directory: ./deepmicroplastic
        run: flutter pub get

      - name: Build do Flutter Web
        working-directory: ./deepmicroplastic
        run: flutter build web --release --base-href "/Sistema/"

      - name: Upload do artefato para o Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './deepmicroplastic/build/web'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy para o GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4